package tamago.aca.bank;
import tamago.ext.tamagocc.*;
import tamago.*;
/*
    
 ******************************************
 *               DepositACA               *
 ******************************************
 *
 * DO NOT EDIT THIS FILE.
 * THIS FILE IS GENERATED AUTOMATICALLY BY TAMAGOCC
 * Created date : Sun Feb 19 21:04:45 CET 2012
 * authors : Hakim Belhaouari and Frederic Peschanski
 * site : http://www-poleia.lip6.fr/~belhaouari/Tamago/

*/
public class DepositACAContainerImpl_plugin
     extends tamago.ext.tamagocc.TamagoCCContainerImpl
    implements tamago.aca.bank.DepositACAContainer
{
    // Members Variables
    private tamago.aca.bank.DepositACA tamago_decorated_component;

    // Properties
    /**
        Getter of the property historic
    */
    public tamago.ext.aca2.Historic getHistoric(){
        return tamago_decorated_component.getHistoric();
    }

    // Methods
    /*
        Don't modify this constructor !

    */
    public DepositACAContainerImpl_plugin (tamago.aca.bank.DepositACA component)
    {
        tamago_decorated_component = ((tamago.aca.bank.DepositACA) component);
        // ----- if necessary you can add some code under this ligne ----
    }


    public RequiredService[] getRequiredServices(){
        RequiredService[] rs = new RequiredService[1];
        rs[0] = new RequiredService("Deposit", "tamago.aca.bank", "acamodel");
        return rs;
    }


    public void bind(String label, TamagoCCService service) throws ServiceBindException{
        tamago_decorated_component.bind(label, service);
    }


    public boolean isBound(){
        return (tamago_decorated_component == null);
    }


    public boolean isBound(String label){
        if(label.equals("acamodel")) {
            return (acamodel() != null);
        }
        return false;
    }


    public void core_set_properties(String property, Object value){
        throw new TamagoCCHotSwappingException();
    }


    public void tamago_hotswapping(TamagoCCComponent component){
        tamago.ext.aca2.Historic sav_historic = getHistoric();
        tamago_decorated_component = ((tamago.aca.bank.DepositACA) component);
        tamago_decorated_component.core_set_properties("historic", sav_historic);
    }


    public void validate_director(int clid, int cid, tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_1 = (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org)));
        if(!__tamago_var_perco_1) {
            java.util.ArrayList __tamago_var_perco_0 = new java.util.ArrayList();
            if(!__tamago_var_perco_1) {
                __tamago_var_perco_0.add(new tamago.ext.tamagocc.TamagoCCFailItem("((((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_0);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.validate_director(clid, cid, aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void check(int clid, int cid, tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_5 = (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org)));
        if(!__tamago_var_perco_5) {
            java.util.ArrayList __tamago_var_perco_4 = new java.util.ArrayList();
            if(!__tamago_var_perco_5) {
                __tamago_var_perco_4.add(new tamago.ext.tamagocc.TamagoCCFailItem("((((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_4);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.check(clid, cid, aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void cancel(int clid, int cid, tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_9 = ("banker".equals(aca.role) && "director".equals(aca.role) && !"elisa".equals(aca.user) && !"customer".equals(aca.role) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))));
        if(!__tamago_var_perco_9) {
            java.util.ArrayList __tamago_var_perco_8 = new java.util.ArrayList();
            if(!__tamago_var_perco_9) {
                __tamago_var_perco_8.add(new tamago.ext.tamagocc.TamagoCCFailItem("(((aca.role == \"banker\")) and ((aca.role == \"director\")) and ((aca.user != \"elisa\")) and ((aca.role != \"customer\")) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_8);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.cancel(clid, cid, aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void deposit(int clid, int cid, tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_13 = ("clerk".equals(aca.role) && "banker".equals(aca.role) && !"customer".equals(aca.role) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))));
        if(!__tamago_var_perco_13) {
            java.util.ArrayList __tamago_var_perco_12 = new java.util.ArrayList();
            if(!__tamago_var_perco_13) {
                __tamago_var_perco_12.add(new tamago.ext.tamagocc.TamagoCCFailItem("(((aca.role == \"clerk\")) and ((aca.role == \"banker\")) and ((aca.role != \"customer\")) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_12);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.deposit(clid, cid, aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void validate(int clid, int cid, tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_17 = ("banker".equals(aca.role) && "director".equals(aca.role) && !"Toronto".equals(aca.org) && !"customer".equals(aca.role) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))));
        if(!__tamago_var_perco_17) {
            java.util.ArrayList __tamago_var_perco_16 = new java.util.ArrayList();
            if(!__tamago_var_perco_17) {
                __tamago_var_perco_16.add(new tamago.ext.tamagocc.TamagoCCFailItem("(((aca.role == \"banker\")) and ((aca.role == \"director\")) and ((aca.org != \"Toronto\")) and ((aca.role != \"customer\")) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_16);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.validate(clid, cid, aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void register(int clid, int cid, tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_21 = (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org)));
        if(!__tamago_var_perco_21) {
            java.util.ArrayList __tamago_var_perco_20 = new java.util.ArrayList();
            if(!__tamago_var_perco_21) {
                __tamago_var_perco_20.add(new tamago.ext.tamagocc.TamagoCCFailItem("((((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_20);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.register(clid, cid, aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    /**
        This method allow user to access to the required service.(You do not need to implement this method, TamagoCC generates it in the skeleton)
    */
    public tamago.aca.bank.Deposit acamodel(){
        return tamago_decorated_component.acamodel();
    }
}