//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.02.23 at 06:50:34 PM CET 
//


package fr.lacl.tamago.aca.xmlterm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Term complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Term">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="atomic" type="{}atomic"/>
 *         &lt;element name="sod" type="{}sod"/>
 *         &lt;element name="obl" type="{}obl"/>
 *         &lt;element name="parstrong" type="{}parstrong"/>
 *         &lt;element name="parweak" type="{}parweak"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Term", propOrder = {
    "atomic",
    "sod",
    "obl",
    "parstrong",
    "parweak"
})
public class Term {

    protected Atomic atomic;
    protected Sod sod;
    protected Obl obl;
    protected Parstrong parstrong;
    protected Parweak parweak;

    /**
     * Gets the value of the atomic property.
     * 
     * @return
     *     possible object is
     *     {@link Atomic }
     *     
     */
    public Atomic getAtomic() {
        return atomic;
    }

    /**
     * Sets the value of the atomic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Atomic }
     *     
     */
    public void setAtomic(Atomic value) {
        this.atomic = value;
    }

    /**
     * Gets the value of the sod property.
     * 
     * @return
     *     possible object is
     *     {@link Sod }
     *     
     */
    public Sod getSod() {
        return sod;
    }

    /**
     * Sets the value of the sod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Sod }
     *     
     */
    public void setSod(Sod value) {
        this.sod = value;
    }

    /**
     * Gets the value of the obl property.
     * 
     * @return
     *     possible object is
     *     {@link Obl }
     *     
     */
    public Obl getObl() {
        return obl;
    }

    /**
     * Sets the value of the obl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Obl }
     *     
     */
    public void setObl(Obl value) {
        this.obl = value;
    }

    /**
     * Gets the value of the parstrong property.
     * 
     * @return
     *     possible object is
     *     {@link Parstrong }
     *     
     */
    public Parstrong getParstrong() {
        return parstrong;
    }

    /**
     * Sets the value of the parstrong property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parstrong }
     *     
     */
    public void setParstrong(Parstrong value) {
        this.parstrong = value;
    }

    /**
     * Gets the value of the parweak property.
     * 
     * @return
     *     possible object is
     *     {@link Parweak }
     *     
     */
    public Parweak getParweak() {
        return parweak;
    }

    /**
     * Sets the value of the parweak property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parweak }
     *     
     */
    public void setParweak(Parweak value) {
        this.parweak = value;
    }

}
