package tamago.aca;
/*
    
 ******************************************
 *             VBanqueCompACA             *
 ******************************************
 *
 * DO NOT EDIT THIS FILE.
 * THIS FILE IS GENERATED AUTOMATICALLY BY TAMAGOCC
 * Created date : Fri Apr 22 11:41:23 CEST 2011
 * authors : Hakim Belhaouari and Frederic Peschanski
 * site : http://www-poleia.lip6.fr/~belhaouari/Tamago/

*/
public interface VBanqueCompACAContainer
    extends tamago.aca.VBanqueCompACA, tamago.ext.tamagocc.TamagoCCContainer
{
    // Members Variables

    // Properties

    // Methods
    public void deposit(tamago.ext.aca.Quad quad) throws tamago.TamagoException;


    public void modify(tamago.ext.aca.Quad quad) throws tamago.TamagoException;


    public void validate(tamago.ext.aca.Quad quad) throws tamago.TamagoException;
}