package tamago.aca.bank;
import tamago.ext.tamagocc.*;
import tamago.*;
import tamago.ext.tamagoaca2.*;
/*
    
 ******************************************
 *            DepositSecurity            *
 ******************************************
 *
 * DO NOT EDIT THIS FILE.
 * THIS FILE IS GENERATED AUTOMATICALLY BY TAMAGOCC
 * Created date : Thu Feb 23 23:40:46 CET 2012
 * authors : Hakim Belhaouari and Frederic Peschanski
 * site : http://code.google.com/p/tamago/

*/
public class DepositSecurityContainerACASecurity
{
    // Members Variables
    private tamago.aca.bank.DepositSecurity tamago_decorated_component;

    // Properties
    /**
        Getter of the property opNumber
    */
    public int getOpNumber(){
        return tamago_decorated_component.getOpNumber();
    }
    /**
        Getter of the property acaInitialised
    */
    public boolean getAcaInitialised(){
        return tamago_decorated_component.getAcaInitialised();
    }
    /**
        Setter of the property acaInitialised
    */
    public void setAcaInitialised(boolean acaInitialised){
        tamago_decorated_component.setAcaInitialised(acaInitialised);
    }
    /**
        Getter of the property play
    */
    public tamago.ext.aca2.Play getPlay(){
        return tamago_decorated_component.getPlay();
    }
    /**
        Getter of the property historic
    */
    public tamago.ext.aca2.Historic getHistoric(){
        return tamago_decorated_component.getHistoric();
    }

    // Methods
    /*
        Don't modify this constructor !

    */
    public DepositSecurityContainerACASecurity (tamago.aca.bank.DepositSecurity component)
    {
        tamago_decorated_component = ((tamago.aca.bank.DepositSecurity) component);
        // ----- if necessary you can add some code under this ligne ----
    }


    public RequiredService[] getRequiredServices(){
        RequiredService[] rs = new RequiredService[0];
        return rs;
    }


    public void bind(String label, TamagoCCService service) throws ServiceBindException{
        tamago_decorated_component.bind(label, service);
    }


    public boolean isBound(){
        return (tamago_decorated_component == null);
    }


    public boolean isBound(String label){
        return false;
    }


    public void core_set_properties(String property, Object value){
        throw new TamagoCCHotSwappingException();
    }


    public void tamago_hotswapping(TamagoCCComponent component){
        int sav_opNumber = getOpNumber();
        boolean sav_acaInitialised = getAcaInitialised();
        tamago.ext.aca2.Play sav_play = getPlay();
        tamago.ext.aca2.Historic sav_historic = getHistoric();
        tamago_decorated_component = ((tamago.aca.bank.DepositSecurity) component);
        tamago_decorated_component.core_set_properties("opNumber", sav_opNumber);
        tamago_decorated_component.core_set_properties("acaInitialised", sav_acaInitialised);
        tamago_decorated_component.core_set_properties("play", sav_play);
        tamago_decorated_component.core_set_properties("historic", sav_historic);
    }


    public void cancel(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.cancel(aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void check(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.check(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_7 = (tamago_decorated_component.getOpNumber() > 0);
        if(!__tamago_var_perco_7) {
            java.util.ArrayList __tamago_var_perco_6 = new java.util.ArrayList();
            if(!__tamago_var_perco_7) {
                __tamago_var_perco_6.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#opNumber > 0)"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_6);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void validate(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.validate(aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void register(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.register(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_15 = (tamago_decorated_component.getOpNumber() > 0);
        if(!__tamago_var_perco_15) {
            java.util.ArrayList __tamago_var_perco_14 = new java.util.ArrayList();
            if(!__tamago_var_perco_15) {
                __tamago_var_perco_14.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#opNumber > 0)"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_14);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void validate_director(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.validate_director(aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void deposit(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.deposit(aca);
        // Environment of Postcondition
        // Postcondition test
        // No postcondition detected
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void init() throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.init();
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_27 = (opNumber < 0);
        if(!__tamago_var_perco_27) {
            java.util.ArrayList __tamago_var_perco_26 = new java.util.ArrayList();
            if(!__tamago_var_perco_27) {
                __tamago_var_perco_26.add(new tamago.ext.tamagocc.TamagoCCFailItem("(opNumber < 0)"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_26);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }
}