package tamago.aca.bank;
import tamago.ext.tamagocc.*;
import tamago.*;
import tamago.ext.tamagoaca2.*;
/*
    
 ******************************************
 *            DepositSecurity            *
 ******************************************
 *
 * DO NOT EDIT THIS FILE.
 * THIS FILE IS GENERATED AUTOMATICALLY BY TAMAGOCC
 * Created date : Wed Feb 29 21:30:49 CET 2012
 * authors : Hakim Belhaouari and Frederic Peschanski
 * site : http://code.google.com/p/tamago/

*/
public class DepositSecurityContainerACASecurity
{
    // Members Variables
    private tamago.aca.bank.DepositSecurity tamago_decorated_component;

    // Properties
    /**
        Getter of the property opNumber
    */
    public int getOpNumber(){
        return tamago_decorated_component.getOpNumber();
    }
    /**
        Getter of the property acaInitialised
    */
    public boolean getAcaInitialised(){
        return tamago_decorated_component.getAcaInitialised();
    }
    /**
        Setter of the property acaInitialised
    */
    public void setAcaInitialised(boolean acaInitialised){
        tamago_decorated_component.setAcaInitialised(acaInitialised);
    }
    /**
        Getter of the property play
    */
    public tamago.ext.aca2.Play getPlay(){
        return tamago_decorated_component.getPlay();
    }
    /**
        Getter of the property historic
    */
    public tamago.ext.aca2.Historic getHistoric(){
        return tamago_decorated_component.getHistoric();
    }

    // Methods
    /*
        Don't modify this constructor !

    */
    public DepositSecurityContainerACASecurity (tamago.aca.bank.DepositSecurity component)
    {
        tamago_decorated_component = ((tamago.aca.bank.DepositSecurity) component);
        // ----- if necessary you can add some code under this ligne ----
    }


    public RequiredService[] getRequiredServices(){
        RequiredService[] rs = new RequiredService[0];
        return rs;
    }


    public void bind(String label, TamagoCCService service) throws ServiceBindException{
        tamago_decorated_component.bind(label, service);
    }


    public boolean isBound(){
        return (tamago_decorated_component == null);
    }


    public boolean isBound(String label){
        return false;
    }


    public void core_set_properties(String property, Object value){
        throw new TamagoCCHotSwappingException();
    }


    public void tamago_hotswapping(TamagoCCComponent component){
        int sav_opNumber = getOpNumber();
        boolean sav_acaInitialised = getAcaInitialised();
        tamago.ext.aca2.Play sav_play = getPlay();
        tamago.ext.aca2.Historic sav_historic = getHistoric();
        tamago_decorated_component = ((tamago.aca.bank.DepositSecurity) component);
        tamago_decorated_component.core_set_properties("opNumber", sav_opNumber);
        tamago_decorated_component.core_set_properties("acaInitialised", sav_acaInitialised);
        tamago_decorated_component.core_set_properties("play", sav_play);
        tamago_decorated_component.core_set_properties("historic", sav_historic);
    }


    public void deposit(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_2 = (tamago_decorated_component.getPlay().isCorrectACA(aca) && "clerk".equals(aca.role) && "banker".equals(aca.role) && !"customer".equals(aca.role) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))));
        if(!__tamago_var_perco_2) {
            java.util.ArrayList __tamago_var_perco_0 = new java.util.ArrayList();
            if(!__tamago_var_perco_2) {
                __tamago_var_perco_0.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#play.isCorrectACA(aca) and ((aca.role == \"clerk\")) and ((aca.role == \"banker\")) and ((aca.role != \"customer\")) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_0);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.deposit(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_5 = ("deposit".equals(tamago_decorated_component.getHistoric().lastAction()) && aca.equals(tamago_decorated_component.getHistoric().lastSecuParam()));
        if(!__tamago_var_perco_5) {
            java.util.ArrayList __tamago_var_perco_3 = new java.util.ArrayList();
            if(!__tamago_var_perco_5) {
                __tamago_var_perco_3.add(new tamago.ext.tamagocc.TamagoCCFailItem("((\"deposit\" == #historic.lastAction()) and (aca == #historic.lastSecuParam()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_3);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void register(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_8 = (tamago_decorated_component.getPlay().isCorrectACA(aca) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))) && tamago_decorated_component.getHistoric().mustDone("deposit") && (tamago_decorated_component.getHistoric().getSecuParamFromID("deposit").getUser() == aca.user));
        if(!__tamago_var_perco_8) {
            java.util.ArrayList __tamago_var_perco_6 = new java.util.ArrayList();
            if(!__tamago_var_perco_8) {
                __tamago_var_perco_6.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#play.isCorrectACA(aca) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))) and #historic.mustDone(\"deposit\") and (#historic.getSecuParamFromID(\"deposit\").getUser() == aca.user))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_6);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.register(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_10 = (tamago_decorated_component.getOpNumber() > 0);
        boolean __tamago_var_perco_11 = ("register".equals(tamago_decorated_component.getHistoric().lastAction()) && aca.equals(tamago_decorated_component.getHistoric().lastSecuParam()));
        if(!(__tamago_var_perco_10 && __tamago_var_perco_11)) {
            java.util.ArrayList __tamago_var_perco_9 = new java.util.ArrayList();
            if(!__tamago_var_perco_10) {
                __tamago_var_perco_9.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#opNumber > 0)"));
            }
            if(!__tamago_var_perco_11) {
                __tamago_var_perco_9.add(new tamago.ext.tamagocc.TamagoCCFailItem("((\"register\" == #historic.lastAction()) and (aca == #historic.lastSecuParam()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_9);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void init() throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        // No precondition detected
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.init();
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_16 = (tamago_decorated_component.getOpNumber() < 0);
        boolean __tamago_var_perco_17 = acaInitialised;
        if(!(__tamago_var_perco_16 && __tamago_var_perco_17)) {
            java.util.ArrayList __tamago_var_perco_15 = new java.util.ArrayList();
            if(!__tamago_var_perco_16) {
                __tamago_var_perco_15.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#opNumber < 0)"));
            }
            if(!__tamago_var_perco_17) {
                __tamago_var_perco_15.add(new tamago.ext.tamagocc.TamagoCCFailItem("acaInitialised"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_15);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void validate_director(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_20 = (tamago_decorated_component.getPlay().isCorrectACA(aca) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))) && tamago_decorated_component.getHistoric().mustDone("validate") && (aca.user != tamago_decorated_component.getHistoric().getSecuParamFromID("validate").getUser()));
        if(!__tamago_var_perco_20) {
            java.util.ArrayList __tamago_var_perco_18 = new java.util.ArrayList();
            if(!__tamago_var_perco_20) {
                __tamago_var_perco_18.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#play.isCorrectACA(aca) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))) and #historic.mustDone(\"validate\") and (aca.user != #historic.getSecuParamFromID(\"validate\").getUser()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_18);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.validate_director(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_23 = ("validate_dir".equals(tamago_decorated_component.getHistoric().lastAction()) && aca.equals(tamago_decorated_component.getHistoric().lastSecuParam()));
        if(!__tamago_var_perco_23) {
            java.util.ArrayList __tamago_var_perco_21 = new java.util.ArrayList();
            if(!__tamago_var_perco_23) {
                __tamago_var_perco_21.add(new tamago.ext.tamagocc.TamagoCCFailItem("((\"validate_dir\" == #historic.lastAction()) and (aca == #historic.lastSecuParam()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_21);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void cancel(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_26 = (tamago_decorated_component.getPlay().isCorrectACA(aca) && "banker".equals(aca.role) && "director".equals(aca.role) && !"elisa".equals(aca.user) && !"customer".equals(aca.role) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))) && tamago_decorated_component.getHistoric().mustDone("deposit") && (tamago_decorated_component.getHistoric().getSecuParamFromID("deposit").getUser() == aca.user));
        if(!__tamago_var_perco_26) {
            java.util.ArrayList __tamago_var_perco_24 = new java.util.ArrayList();
            if(!__tamago_var_perco_26) {
                __tamago_var_perco_24.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#play.isCorrectACA(aca) and ((aca.role == \"banker\")) and ((aca.role == \"director\")) and ((aca.user != \"elisa\")) and ((aca.role != \"customer\")) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))) and #historic.mustDone(\"deposit\") and (#historic.getSecuParamFromID(\"deposit\").getUser() == aca.user))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_24);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.cancel(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_29 = ("cancel".equals(tamago_decorated_component.getHistoric().lastAction()) && aca.equals(tamago_decorated_component.getHistoric().lastSecuParam()));
        if(!__tamago_var_perco_29) {
            java.util.ArrayList __tamago_var_perco_27 = new java.util.ArrayList();
            if(!__tamago_var_perco_29) {
                __tamago_var_perco_27.add(new tamago.ext.tamagocc.TamagoCCFailItem("((\"cancel\" == #historic.lastAction()) and (aca == #historic.lastSecuParam()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_27);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void check(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_32 = (tamago_decorated_component.getPlay().isCorrectACA(aca) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))));
        if(!__tamago_var_perco_32) {
            java.util.ArrayList __tamago_var_perco_30 = new java.util.ArrayList();
            if(!__tamago_var_perco_32) {
                __tamago_var_perco_30.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#play.isCorrectACA(aca) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_30);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.check(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_34 = (tamago_decorated_component.getOpNumber() > 0);
        boolean __tamago_var_perco_35 = ("check".equals(tamago_decorated_component.getHistoric().lastAction()) && aca.equals(tamago_decorated_component.getHistoric().lastSecuParam()));
        if(!(__tamago_var_perco_34 && __tamago_var_perco_35)) {
            java.util.ArrayList __tamago_var_perco_33 = new java.util.ArrayList();
            if(!__tamago_var_perco_34) {
                __tamago_var_perco_33.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#opNumber > 0)"));
            }
            if(!__tamago_var_perco_35) {
                __tamago_var_perco_33.add(new tamago.ext.tamagocc.TamagoCCFailItem("((\"check\" == #historic.lastAction()) and (aca == #historic.lastSecuParam()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_33);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }


    public void validate(tamago.ext.aca2.ACA aca) throws tamago.TamagoException{
        // Initialisation of variables
        // Invariant test before precondition
        // Environment of Precondition
        // Precondition test
        boolean __tamago_var_perco_38 = (tamago_decorated_component.getPlay().isCorrectACA(aca) && "banker".equals(aca.role) && "director".equals(aca.role) && !"Toronto".equals(aca.org) && !"customer".equals(aca.role) && (("alphonse".equals(aca.user) || "boris".equals(aca.user) || "catherine".equals(aca.user) || "damien".equals(aca.user) || "elise".equals(aca.user) || "franck".equals(aca.user)) && ("customer".equals(aca.role) || "clerk".equals(aca.role) || "banker".equals(aca.role) || "director".equals(aca.role)) && ("montreal".equals(aca.org) || "toronto".equals(aca.org))) && tamago_decorated_component.getHistoric().mustDone("deposit") && (aca.user != tamago_decorated_component.getHistoric().getSecuParamFromID("deposit").getUser()));
        if(!__tamago_var_perco_38) {
            java.util.ArrayList __tamago_var_perco_36 = new java.util.ArrayList();
            if(!__tamago_var_perco_38) {
                __tamago_var_perco_36.add(new tamago.ext.tamagocc.TamagoCCFailItem("(#play.isCorrectACA(aca) and ((aca.role == \"banker\")) and ((aca.role == \"director\")) and ((aca.org != \"Toronto\")) and ((aca.role != \"customer\")) and (((aca.user == \"alphonse\") or (aca.user == \"boris\") or (aca.user == \"catherine\") or (aca.user == \"damien\") or (aca.user == \"elise\") or (aca.user == \"franck\")) and ((aca.role == \"customer\") or (aca.role == \"clerk\") or (aca.role == \"banker\") or (aca.role == \"director\")) and ((aca.org == \"montreal\") or (aca.org == \"toronto\"))) and #historic.mustDone(\"deposit\") and (aca.user != #historic.getSecuParamFromID(\"deposit\").getUser()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPrecondition(__tamago_var_perco_36);
        }
        // Initialisation of at pre expression
        // redirect call
        tamago_decorated_component.validate(aca);
        // Environment of Postcondition
        // Postcondition test
        boolean __tamago_var_perco_41 = ("validate".equals(tamago_decorated_component.getHistoric().lastAction()) && aca.equals(tamago_decorated_component.getHistoric().lastSecuParam()));
        if(!__tamago_var_perco_41) {
            java.util.ArrayList __tamago_var_perco_39 = new java.util.ArrayList();
            if(!__tamago_var_perco_41) {
                __tamago_var_perco_39.add(new tamago.ext.tamagocc.TamagoCCFailItem("((\"validate\" == #historic.lastAction()) and (aca == #historic.lastSecuParam()))"));
            }
            throw new tamago.ext.tamagocc.TamagoCCFailPostcondition(__tamago_var_perco_39);
        }
        // Invariant test after postcondition
        // Update behavioral's state
        // Return of the redirect method if needed
    }
}